export const initialState = {
  posts: {
    data: [
      {
        id: '1',
        title: 'Apartment for sale $500.000',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et turpis a sapien luctus ullamcorper gravida vel lectus. Vivamus sed ipsum dapibus, placerat magna in, elementum erat.',
        date: '13.08.2021',
        updateDate: '10.09.2021',
        email: 'johndoe@example.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/2459/stairs-home-loft-lifestyle.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      },
      {
        id: '2',
        title: 'Apartment for rent',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et turpis a sapien luctus ullamcorper gravida vel lectus. Vivamus sed ipsum dapibus, placerat magna in, elementum erat.',
        date: '05.07.2021',
        updateDate: '05.07.2021',
        email: 'jennydoe@example.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/2459/stairs-home-loft-lifestyle.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      },
      {
        id: '3',
        title: 'I have room to share $300',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et turpis a sapien luctus ullamcorper gravida vel lectus. Vivamus sed ipsum dapibus, placerat magna in, elementum erat.',
        date: '20.09.2020',
        updateDate: '25.09.2020',
        email: 'jessicadoe@example.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/2459/stairs-home-loft-lifestyle.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      },
      {
        id: '4',
        title: 'Looking for an apartment',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et turpis a sapien luctus ullamcorper gravida vel lectus. Vivamus sed ipsum dapibus, placerat magna in, elementum erat.',
        date: '10.08.2021',
        updateDate: '13.09.2021',
        email: 'johndoe@example.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/2459/stairs-home-loft-lifestyle.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      },
      {
        id: '5',
        title: 'A falt for sale',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et turpis a sapien luctus ullamcorper gravida vel lectus. Vivamus sed ipsum dapibus, placerat magna in, elementum erat.',
        date: '20.06.2020',
        updateDate: '02.08.2020',
        email: 'jessicadoe@example.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/2459/stairs-home-loft-lifestyle.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  logged: false,
};
